services:
  simple-jwt-login-documentation:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    ports: 
      - 3002:3000  
    network_mode: bridge     
       