import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    'Introduction',
    'Dashboard',
    'Configuration',
    {
      type: 'category',
      label: 'Routes',
      collapsed: false,
      items: [
        'Login-User',
        'Register-User',
        'Delete-User',
        {
          type: 'category',
          label: 'Reset Password',
          items: [
            'reset_password/Reset-Password',
            'reset_password/ChangePassword',
          ],
        },
        'auth/Authentication',
        'auth/RefreshToken',
        'auth/ValidateToken',
        'auth/RevokeToken',
      ],
    },
    {
      type: 'category',
      label: 'Security',
      collapsed: false,
      items: [
        'Auth-Codes',
        'Protect-Endpoints',
        'Cors',
        'API-Keys',
      ],
    },
    {
      type: 'category',
      label: 'Integrations',
      collapsed: false,
      items: [
        'integrations/OAuth',
        'integrations/ThirdParty',
        'OAuth',
        {
          type: 'category',
          label: 'Google',
          items: [
            'integrations/Google/Setup',
            'integrations/Google/Social_Login',
            'integrations/Google/Code_to_id_token',
            'integrations/Google/id_token_to_JWT',
            'integrations/Google/Shortcode',
          ],
        },
        'integrations/CLI',
        'integrations/ExportImport',
        'integrations/MailPoet',
        'integrations/WPGraphQL',
      ],
    },
    'Webhooks',
    'AuditLogs',
    'Hooks',
    'Error-Codes',
    {
      type: 'category',
      label: 'Code Examples',
      items: [
        {type: 'autogenerated', dirName: 'code_examples'},
      ],
    },
  ],
};

export default sidebars;
