import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    'Introduction',
    'Dashboard',
    'Configuration',
    {
      type: 'category',
      label: 'Routes',
      collapsed: false,
      items: [
        'Login-User',
        'Register-User',
        'Delete-User',
        'Reset-Password',
        'auth/Authentication',
        'auth/RefreshToken',
        'auth/ValidateToken',
        'auth/RevokeToken',
      ],
    },
    {
      type: 'category',
      label: 'Security',
      collapsed: false,
      items: [
        'Auth-Codes',
        'Protect-Endpoints',
        'Cors',
        'API-Keys',
      ],
    },
    {
      type: 'category',
      label: 'Integrations',
      collapsed: false,
      items: [
        {
          type: 'category',
          label: 'OAuth',
          link: {type: 'doc', id: 'integrations/OAuth/index'},
          items: [
            {
              type: 'category',
              label: 'Google',
              items: [
                'integrations/OAuth/Google/Setup',
                'integrations/OAuth/Google/Exchange_Code',
                'integrations/OAuth/Google/Exchange_Token',
                'integrations/OAuth/Google/Shortcode',
              ],
            },
            {
              type: 'category',
              label: 'Auth0',
              items: [
                'integrations/OAuth/Auth0/Setup',
                'integrations/OAuth/Auth0/Exchange_Code',
                'integrations/OAuth/Auth0/Exchange_Token',
              ],
            },
            {
              type: 'category',
              label: 'Facebook',
              items: [
                'integrations/OAuth/Facebook/Setup',
                'integrations/OAuth/Facebook/Exchange_Code',
                'integrations/OAuth/Facebook/Exchange_Token',
              ],
            },
            {
              type: 'category',
              label: 'GitHub',
              items: [
                'integrations/OAuth/Github/Setup',
                'integrations/OAuth/Github/Exchange_Code',
                'integrations/OAuth/Github/Exchange_Token',
              ],
            },
          ],
        },
        {
          type: 'category',
          label: 'Third Party',
          link: {type: 'doc', id: 'integrations/ThirdParty/index'},
          items: [
            'integrations/ThirdParty/WPGraphQL',
            'integrations/ThirdParty/TwoFactor',
            'integrations/ThirdParty/ForceLogin',
            'integrations/ThirdParty/WooCommerce',
          ],
        },
      ],
    },
    'Webhooks',
    'AuditLogs',
    'Hooks',
    'Error-Codes',
    {
      type: 'category',
      label: 'Add-ons',
      collapsed: false,
      items: [
        'integrations/MailPoet',
        'integrations/CLI',
        'integrations/ExportImport',
      ],
    },
    {
      type: 'category',
      label: 'Code Examples',
      items: [
        {type: 'autogenerated', dirName: 'code_examples'},
      ],
    },
  ],
};

export default sidebars;
