name: CI-validate

on:
  push:
    branches: [ "main" ]

jobs:
  check-build:
    runs-on: ubuntu-latest
    steps:
      - name: 🛎️ Checkout
        uses: actions/checkout@v4

      - name: 🧑‍💻 Setup
        run: |
          yarn install

      - name: 📚 Spellcheck 
        run: yarn spellcheck

      - name: 🔧 Check Install and Build 
        run: |
          yarn gen-api
          yarn build
          
      